basePath: /application
host: localhost:8080
info:
  contact: {}
  description: Contains all the apis for user (postgres database).
  title: User Application APIs
  version: "1.0"
paths:
  /application/user:
    get:
      description: Access a protected route.
      responses:
        "200":
          description: OK
          schema:
            type: object
      security:
      - BearerAuth: []
      summary: Protected Route
      tags:
      - Protected
swagger: "2.0"
